#!/bin/bash
alarm_flags=()

while getopts aAeEp: opt; do
  case $opt in
    [aAeE])
      alarm_flags+=("-$opt")
      ;;
    [p])
      alarm_flags+=("-$opt" "$OPTARG")
      ;;
  esac
done

shift $((OPTIND-1))

echo "alarm.sh" "${alarm_flags[@]}" | at "$@"
