#!/bin/sh

OUTPUT=${1:-VGA1}
MAIN=LVDS1
panelsdir="$HOME/.config/lxpanel/default/panels"

xrandr | grep "^$OUTPUT connected" || { echo "$OUTPUT is not connected!" >&2 ; exit 1; }

# enable other monitor
xrandr --output "$OUTPUT" --preferred --right-of "$MAIN" || xrandr --output "$OUTPUT" --auto --right-of "$MAIN" || exit

# lxpanel on other monitor
cd "$panelsdir"
cp panel alternate
patch panel <<EOF >/dev/null
--- panel	2015-05-05 22:46:40.951040255 -0400
+++ alternate	2015-06-14 01:42:47.389109094 -0400
@@ -106,11 +106,11 @@
     Size=2
   }
 }
-Plugin {
-  type=pager
-  Config {
-  }
-}
+#Plugin {
+#  type=pager
+#  Config {
+#  }
+#}
 Plugin {
   type=space
   Config {
EOF
sed -i 's/monitor=0/monitor=1/' alternate
mv panel.orig /tmp/

lxpanelctl restart
