#!/bin/sh

OUTPUT=${1:-VGA1}

# disable panel on other display
rm ~/.config/lxpanel/default/panels/alternate
patch ~/.config/lxpanel/default/panels/panel <<EOF >/dev/null
--- panel	2015-05-05 22:46:40.951040255 -0400
+++ alternate	2015-06-14 01:42:47.389109094 -0400
@@ -106,11 +106,11 @@
     Size=2
   }
 }
-#Plugin {
-#  type=pager
-#  Config {
-#  }
-#}
+Plugin {
+  type=pager
+  Config {
+  }
+}
 Plugin {
   type=space
   Config {
EOF

# don't delete just in case
mv ~/.config/lxpanel/default/panels/panel.orig /tmp/

lxpanelctl restart

# disable other monitor
xrandr --output "$OUTPUT" --off
