#!/bin/sh

# Based on script from <http://blog.pkh.me/p/21-high-quality-gif-with-ffmpeg.html> 

fps=15
scale=640

while getopts f:s: opt; do
  case $opt in
    f)
      fps=$OPTARG
      ;;
    s)
      scale=$OPTARG
      ;;
  esac
done

shift $((OPTIND-1))

palette=$(mktemp --suffix=.png)

filters="fps=$fps,scale=$scale:-1:flags=lanczos"

ffmpeg -v warning -i "$1" -vf "$filters,palettegen" -y "$palette"
ffmpeg -v warning -i "$1" -i "$palette" -lavfi "$filters [x]; [x][1:v] paletteuse" -y "$2"

rm "$palette"
