#!/bin/sh

editor=cat

edit() { cat >"$1"; }

while getopts e opt; do
  case $opt in
    e) edit() { $EDITOR "$1"; } ;;
  esac
done

shift $(( OPTIND - 1 ))

[ $# -eq 1 ] || { echo "ERROR: must specify a filename." >&2; exit 1; }

edit "$1" && chmod +x "$1"
