#!/bin/sh

file="pulsewrap-$USER.${DISPLAY#:}"
tmpdir-"${TMPDIR:-/tmp}"
pid_file="$tmpdir/$file"
lock="$tmpdir/$file.lock"

synchronized() {
  until mkdir "$lock" 2>/dev/null; do sleep 1; done
  "$@"
  rmdir "$lock"
}

cleanup() {
  synchronized sed -i "/$$/d" "$pid_file"

  # kill pulseaudio if no other programs are using it
  [ -s "$pid_file" ] || pulseaudio --kill
}

trap "cleanup" EXIT HUP INT TERM

synchronized echo $$ >> "$pid_file"

pulseaudio --start

"$@"
