#!/bin/sh

file="pulsewrap-$USER.${DISPLAY#:}"
pid_file="/tmp/$file"
lock="/tmp/$file.lock"

synchronized() {
  until mkdir "$lock" 2>/dev/null; do sleep 1; done
  "$@"
  rmdir "$lock"
}

cleanup() {
  synchronized sed -i "/$$/d" "$pid_file"

  # kill pulseaudio if no other programs are using it
  [ "$(wc -l "$pid_file" | cut -d ' ' -f 1 )" -eq 0 ] && pulseaudio --kill
}

trap "cleanup" EXIT SIGINT SIGTERM

synchronized echo $$ >> "$pid_file"

pulseaudio --start

"$@"
