#!/bin/sh
screensaver=xscreensaver
screensaver_pid="$(pgrep -x -U "$(id -u)" "$screensaver")"
screensaver_state="$(ps -o s= "$screensaver_pid")"

if [ "$screensaver_state" = "T" ]; then
  # stopped; wake it
  kill -CONT $screensaver_pid && notify-send "$screensaver enabled"
else
  # running; stop it
  kill -STOP $screensaver_pid && notify-send "$screensaver disabled"
fi
