#!/bin/sh

grub_cfg="/boot/grub/grub.cfg"
default_linux="linux-zen"
preupdate_commit_message="Commit changes before updating GRUB config"
postupdate_commit_message="Update GRUB config"

[ -w "$grub_cfg" ] || { echo "Permission denied: no write access to ${grub_cfg}" >&2; exit 1; }

while getopts k:m:M:o: opt; do
  case $opt in
    k)
      default_linux="$OPTARG"
      ;;
    m)
      postupdate_commit_message="$OPTARG"
      ;;
    M)
      preupdate_commit_message="$OPTARG"
      ;;
    o)
      grub_cfg="$OPTARG"
      ;;
  esac
done

shift $(( OPTIND - 1 ))

cd "${grub_cfg%/*}"

[ -d ".git" ] && git commit -am "$preupdate_commit_message"

grub-mkconfig | sed '/^menuentry '\''Arch Linux'\''/,/^}/{/echo/,/initrd/s/linux\(-[-_A-Za-z0-9]*\)\?/'"$default_linux"'/g;s/^\(\s*\)'"$default_linux"'/\1linux/;}' >"$grub_cfg"
echo "Default kernel set to $default_linux"

[ -d ".git" ] && git commit -am "$postupdate_commit_message"
